- hosts: 192.168.1.8
  become: yes
  gather_facts: true
  tasks:      
      - name: Distribution
        debug: msg="{{ ansible_distribution }}"
      - name: "create user and check os Distribution"
        user:
           name: test0
           group: amirreza
           state: present
        when: ansible_distribution == "Ubuntu"
